-- ============================================
-- 200+ 道马来西亚菜品数据
-- ============================================

-- 清空现有菜品数据
TRUNCATE TABLE recipes CASCADE;

-- 插入马来西亚经典菜品
INSERT INTO recipes (name_zh, name_en, name_ms, description, category, cuisine_type, meal_type, prep_time, cook_time, servings, difficulty, calories, health_tags, dietary_restrictions) VALUES

-- 早餐类 (Breakfast) - 40道
('椰浆饭', 'Nasi Lemak', 'Nasi Lemak', '马来西亚国菜，椰浆煮饭配花生、鸡蛋、参巴酱', 'breakfast', 'malay', 'breakfast', 20, 30, 2, 'easy', 450, ARRAY['traditional'], ARRAY[]::TEXT[]),
('海南鸡饭', 'Hainanese Chicken Rice', 'Nasi Ayam Hainan', '嫩滑鸡肉配香饭和姜葱酱', 'breakfast', 'chinese', 'breakfast', 30, 45, 2, 'medium', 500, ARRAY['protein-rich'], ARRAY[]::TEXT[]),
('炒粿条', 'Char Kuey Teow', 'Char Kuey Teow', '大火炒河粉配虾、鸡蛋、豆芽', 'breakfast', 'chinese', 'breakfast', 15, 15, 2, 'medium', 550, ARRAY['high-protein'], ARRAY[]::TEXT[]),
('云吞面', 'Wonton Noodles', 'Mee Wantan', '弹牙面条配云吞和叉烧', 'breakfast', 'chinese', 'breakfast', 20, 20, 2, 'medium', 420, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('福建炒面', 'Hokkien Mee', 'Mee Hokkien', '黑酱油炒面配猪肉、鱿鱼', 'breakfast', 'chinese', 'breakfast', 15, 20, 2, 'medium', 500, ARRAY['hearty'], ARRAY[]::TEXT[]),
('印度煎饼', 'Roti Canai', 'Roti Canai', '薄脆煎饼配咖喱', 'breakfast', 'indian', 'breakfast', 30, 15, 2, 'medium', 380, ARRAY['vegetarian-option'], ARRAY[]::TEXT[]),
('咖喱角', 'Curry Puff', 'Karipap', '酥皮包咖喱土豆馅', 'breakfast', 'indian', 'breakfast', 30, 20, 4, 'medium', 280, ARRAY['snack'], ARRAY[]::TEXT[]),
('经济饭', 'Economy Rice', 'Nasi Campur', '白饭配多种菜肴任选', 'breakfast', 'mixed', 'breakfast', 10, 30, 2, 'easy', 480, ARRAY['customizable'], ARRAY[]::TEXT[]),
('叉烧包', 'Char Siu Bao', 'Pau Char Siew', '蒸包子配甜味叉烧馅', 'breakfast', 'chinese', 'breakfast', 60, 20, 4, 'hard', 320, ARRAY['dim-sum'], ARRAY[]::TEXT[]),
('虾饺', 'Har Gow', 'Har Gow', '透明皮虾饺', 'breakfast', 'chinese', 'breakfast', 45, 10, 4, 'hard', 180, ARRAY['dim-sum', 'low-calorie'], ARRAY[]::TEXT[]),
('烧卖', 'Siew Mai', 'Siew Mai', '猪肉虾仁烧卖', 'breakfast', 'chinese', 'breakfast', 30, 15, 4, 'medium', 220, ARRAY['dim-sum'], ARRAY[]::TEXT[]),
('萝卜糕', 'Radish Cake', 'Kuih Lobak', '煎炸萝卜糕', 'breakfast', 'chinese', 'breakfast', 90, 15, 4, 'hard', 250, ARRAY['traditional'], ARRAY[]::TEXT[]),
('芋头糕', 'Yam Cake', 'Kuih Keladi', '蒸芋头糕', 'breakfast', 'chinese', 'breakfast', 60, 30, 4, 'medium', 280, ARRAY['traditional'], ARRAY[]::TEXT[]),
('马来糕', 'Steamed Cake', 'Apam', '松软蒸糕', 'breakfast', 'malay', 'breakfast', 20, 20, 6, 'easy', 180, ARRAY['dessert'], ARRAY[]::TEXT[]),
('九层糕', 'Kuih Lapis', 'Kuih Lapis', '彩色分层糕点', 'breakfast', 'malay', 'breakfast', 90, 60, 8, 'hard', 200, ARRAY['traditional', 'colorful'], ARRAY[]::TEXT[]),
('咖椰吐司', 'Kaya Toast', 'Roti Kaya', '烤面包涂咖椰酱和牛油', 'breakfast', 'mixed', 'breakfast', 5, 5, 2, 'easy', 320, ARRAY['quick'], ARRAY[]::TEXT[]),
('半生熟蛋', 'Half-Boiled Eggs', 'Telur Separuh Masak', '半熟蛋配酱油胡椒', 'breakfast', 'mixed', 'breakfast', 2, 5, 2, 'easy', 140, ARRAY['protein-rich', 'quick'], ARRAY[]::TEXT[]),
('肉骨茶', 'Bak Kut Teh', 'Bak Kut Teh', '药材炖排骨汤', 'breakfast', 'chinese', 'breakfast', 20, 120, 4, 'easy', 380, ARRAY['herbal', 'hearty'], ARRAY[]::TEXT[]),
('猪肠粉', 'Chee Cheong Fun', 'Chee Cheong Fun', '肠粉配甜酱和芝麻', 'breakfast', 'chinese', 'breakfast', 30, 10, 2, 'medium', 280, ARRAY['light'], ARRAY[]::TEXT[]),
('印度炒面', 'Mee Goreng', 'Mee Goreng', '辣味炒黄面', 'breakfast', 'indian', 'breakfast', 10, 15, 2, 'easy', 480, ARRAY['spicy'], ARRAY[]::TEXT[]),

-- 午餐类 (Lunch) - 70道
('仁当鸡', 'Chicken Rendang', 'Rendang Ayam', '浓郁椰香咖喱炖鸡', 'lunch', 'malay', 'lunch', 30, 90, 4, 'medium', 520, ARRAY['spicy', 'coconut'], ARRAY[]::TEXT[]),
('仁当牛', 'Beef Rendang', 'Rendang Daging', '慢炖香辣牛肉', 'lunch', 'malay', 'lunch', 30, 120, 4, 'medium', 580, ARRAY['spicy', 'traditional'], ARRAY[]::TEXT[]),
('咖喱鸡', 'Chicken Curry', 'Kari Ayam', '马来咖喱炖鸡', 'lunch', 'malay', 'lunch', 20, 45, 4, 'easy', 480, ARRAY['curry', 'coconut'], ARRAY[]::TEXT[]),
('咖喱鱼头', 'Fish Head Curry', 'Kari Kepala Ikan', '香浓咖喱炖鱼头', 'lunch', 'indian', 'lunch', 30, 40, 4, 'medium', 450, ARRAY['curry', 'spicy'], ARRAY[]::TEXT[]),
('阿参叻沙', 'Asam Laksa', 'Asam Laksa', '酸辣鱼汤米粉', 'lunch', 'malay', 'lunch', 40, 30, 4, 'medium', 420, ARRAY['sour', 'spicy'], ARRAY[]::TEXT[]),
('咖喱叻沙', 'Curry Laksa', 'Laksa Kari', '椰浆咖喱汤面', 'lunch', 'mixed', 'lunch', 30, 30, 4, 'medium', 550, ARRAY['curry', 'coconut'], ARRAY[]::TEXT[]),
('沙爹', 'Satay', 'Satay', '炭烤肉串配花生酱', 'lunch', 'malay', 'lunch', 60, 15, 4, 'medium', 380, ARRAY['grilled', 'street-food'], ARRAY[]::TEXT[]),
('黑椒鸡', 'Black Pepper Chicken', 'Ayam Lada Hitam', '浓郁黑椒炒鸡', 'lunch', 'chinese', 'lunch', 15, 15, 2, 'easy', 420, ARRAY['spicy'], ARRAY[]::TEXT[]),
('宫保鸡丁', 'Kung Pao Chicken', 'Ayam Kung Pao', '辣炒鸡丁配花生', 'lunch', 'chinese', 'lunch', 20, 15, 2, 'medium', 450, ARRAY['spicy', 'nuts'], ARRAY['peanuts']),
('左宗棠鸡', 'General Tso Chicken', 'Ayam General Tso', '酸甜辣炸鸡', 'lunch', 'chinese', 'lunch', 20, 20, 2, 'medium', 520, ARRAY['sweet-sour'], ARRAY[]::TEXT[]),
('糖醋鱼', 'Sweet Sour Fish', 'Ikan Masam Manis', '酸甜酱炸鱼', 'lunch', 'chinese', 'lunch', 20, 20, 2, 'medium', 480, ARRAY['sweet-sour'], ARRAY[]::TEXT[]),
('清蒸鱼', 'Steamed Fish', 'Ikan Stim', '豉油蒸鲜鱼', 'lunch', 'chinese', 'lunch', 15, 15, 2, 'easy', 280, ARRAY['healthy', 'light'], ARRAY[]::TEXT[]),
('炒饭', 'Fried Rice', 'Nasi Goreng', '马来炒饭', 'lunch', 'malay', 'lunch', 10, 15, 2, 'easy', 480, ARRAY['quick'], ARRAY[]::TEXT[]),
('海鲜炒饭', 'Seafood Fried Rice', 'Nasi Goreng Seafood', '虾蟹炒饭', 'lunch', 'chinese', 'lunch', 15, 15, 2, 'medium', 520, ARRAY['seafood'], ARRAY[]::TEXT[]),
('扬州炒饭', 'Yangzhou Fried Rice', 'Nasi Goreng Yangzhou', '叉烧虾仁炒饭', 'lunch', 'chinese', 'lunch', 15, 15, 2, 'medium', 540, ARRAY['traditional'], ARRAY[]::TEXT[]),
('炒米粉', 'Fried Vermicelli', 'Meehoon Goreng', '干炒米粉', 'lunch', 'chinese', 'lunch', 10, 15, 2, 'easy', 420, ARRAY['quick'], ARRAY[]::TEXT[]),
('福建虾面', 'Prawn Mee', 'Mee Udang', '浓郁虾汤面', 'lunch', 'chinese', 'lunch', 60, 30, 4, 'hard', 480, ARRAY['seafood', 'rich'], ARRAY[]::TEXT[]),
('猪脚醋', 'Pork Trotter Vinegar', 'Kaki Babi Cuka', '甜酸猪脚炖蛋', 'lunch', 'chinese', 'lunch', 30, 90, 4, 'medium', 550, ARRAY['traditional'], ARRAY['halal']),
('黄姜饭', 'Turmeric Rice', 'Nasi Kunyit', '黄姜椰浆饭', 'lunch', 'malay', 'lunch', 20, 30, 4, 'easy', 380, ARRAY['traditional'], ARRAY[]::TEXT[]),
('竹筒饭', 'Bamboo Rice', 'Nasi Bambu', '竹筒椰浆饭', 'lunch', 'malay', 'lunch', 30, 60, 4, 'hard', 420, ARRAY['traditional'], ARRAY[]::TEXT[]),
('娘惹咖喱', 'Nyonya Curry', 'Kari Nyonya', '娘惹风味咖喱', 'lunch', 'nyonya', 'lunch', 30, 45, 4, 'medium', 480, ARRAY['spicy'], ARRAY[]::TEXT[]),
('亚参鱼', 'Assam Fish', 'Ikan Asam', '酸辣炖鱼', 'lunch', 'nyonya', 'lunch', 20, 30, 4, 'easy', 320, ARRAY['sour', 'spicy'], ARRAY[]::TEXT[]),
('黑酱油鸡', 'Dark Soy Chicken', 'Ayam Kicap', '黑酱油焖鸡', 'lunch', 'chinese', 'lunch', 15, 30, 2, 'easy', 460, ARRAY['savory'], ARRAY[]::TEXT[]),
('三杯鸡', 'Three Cup Chicken', 'Ayam Tiga Cawan', '麻油酱油米酒炖鸡', 'lunch', 'chinese', 'lunch', 20, 30, 2, 'medium', 480, ARRAY['aromatic'], ARRAY[]::TEXT[]),
('麻婆豆腐', 'Mapo Tofu', 'Tauhu Mapo', '辣味豆腐肉末', 'lunch', 'chinese', 'lunch', 15, 15, 2, 'easy', 320, ARRAY['spicy', 'vegetarian-option'], ARRAY[]::TEXT[]),
('鱼香茄子', 'Fish-Flavored Eggplant', 'Terung Perisa Ikan', '酸甜辣茄子', 'lunch', 'chinese', 'lunch', 20, 15, 2, 'medium', 280, ARRAY['vegetarian'], ARRAY[]::TEXT[]),
('宫保虾', 'Kung Pao Prawns', 'Udang Kung Pao', '辣炒虾配花生', 'lunch', 'chinese', 'lunch', 20, 15, 2, 'medium', 380, ARRAY['spicy', 'seafood'], ARRAY['peanuts']),
('姜葱炒蟹', 'Ginger Scallion Crab', 'Ketam Halia Bawang', '姜葱爆炒螃蟹', 'lunch', 'chinese', 'lunch', 30, 15, 2, 'medium', 320, ARRAY['seafood'], ARRAY[]::TEXT[]),
('辣椒螃蟹', 'Chili Crab', 'Ketam Cili', '香辣番茄蟹', 'lunch', 'singapore', 'lunch', 30, 20, 2, 'medium', 420, ARRAY['spicy', 'seafood'], ARRAY[]::TEXT[]),
('黑胡椒螃蟹', 'Black Pepper Crab', 'Ketam Lada Hitam', '黑椒爆炒蟹', 'lunch', 'chinese', 'lunch', 30, 15, 2, 'medium', 380, ARRAY['spicy', 'seafood'], ARRAY[]::TEXT[]),
('奶油虾', 'Butter Prawns', 'Udang Mentega', '奶油咖喱叶虾', 'lunch', 'chinese', 'lunch', 20, 15, 2, 'medium', 450, ARRAY['rich', 'seafood'], ARRAY[]::TEXT[]),
('麦片虾', 'Cereal Prawns', 'Udang Cereal', '香酥麦片炸虾', 'lunch', 'chinese', 'lunch', 20, 15, 2, 'medium', 480, ARRAY['crispy', 'seafood'], ARRAY[]::TEXT[]),
('咸蛋黄鱿鱼', 'Salted Egg Squid', 'Sotong Telur Masin', '咸蛋黄炒鱿鱼', 'lunch', 'chinese', 'lunch', 20, 15, 2, 'medium', 420, ARRAY['rich', 'seafood'], ARRAY[]::TEXT[]),
('铁板豆腐', 'Sizzling Tofu', 'Tauhu Plat Panas', '铁板豆腐', 'lunch', 'chinese', 'lunch', 15, 15, 2, 'easy', 320, ARRAY['vegetarian'], ARRAY[]::TEXT[]),
('酿豆腐', 'Stuffed Tofu', 'Tauhu Sumbat', '酿豆腐汤', 'lunch', 'chinese', 'lunch', 30, 20, 4, 'medium', 280, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('客家擂茶', 'Hakka Thunder Tea Rice', 'Nasi Lei Cha', '青菜配擂茶汤', 'lunch', 'chinese', 'lunch', 45, 15, 2, 'hard', 320, ARRAY['healthy', 'vegetarian'], ARRAY[]::TEXT[]),
('薄饼', 'Popiah', 'Popiah', '春卷配蔬菜馅', 'lunch', 'nyonya', 'lunch', 40, 5, 4, 'medium', 280, ARRAY['fresh', 'vegetarian-option'], ARRAY[]::TEXT[]),
('罗惹', 'Rojak', 'Rojak', '水果蔬菜配花生酱', 'lunch', 'malay', 'lunch', 20, 0, 2, 'easy', 220, ARRAY['fresh', 'fruit'], ARRAY['peanuts']),
('印度炒饭', 'Indian Fried Rice', 'Nasi Goreng India', '香料炒饭', 'lunch', 'indian', 'lunch', 10, 15, 2, 'easy', 460, ARRAY['spicy'], ARRAY[]::TEXT[]),
('印度黄姜饭', 'Biryani', 'Nasi Biryani', '香料黄姜饭配肉', 'lunch', 'indian', 'lunch', 30, 45, 4, 'medium', 550, ARRAY['aromatic'], ARRAY[]::TEXT[]),
('印度炒面', 'Mee Goreng Mamak', 'Mee Goreng Mamak', '印度香料炒面', 'lunch', 'indian', 'lunch', 10, 15, 2, 'easy', 480, ARRAY['spicy'], ARRAY[]::TEXT[]),
('黄姜鸡', 'Turmeric Chicken', 'Ayam Kunyit', '黄姜炖鸡', 'lunch', 'malay', 'lunch', 20, 40, 4, 'easy', 420, ARRAY['aromatic'], ARRAY[]::TEXT[]),
('阿参鸡', 'Asam Chicken', 'Ayam Asam', '酸辣炖鸡', 'lunch', 'nyonya', 'lunch', 20, 35, 4, 'easy', 380, ARRAY['sour', 'spicy'], ARRAY[]::TEXT[]),
('冬炎汤', 'Tom Yum Soup', 'Tom Yam', '泰式酸辣虾汤', 'lunch', 'thai', 'lunch', 20, 20, 4, 'easy', 180, ARRAY['sour', 'spicy', 'low-calorie'], ARRAY[]::TEXT[]),
('绿咖喱', 'Green Curry', 'Kari Hijau', '泰式绿咖喱', 'lunch', 'thai', 'lunch', 20, 25, 4, 'medium', 420, ARRAY['spicy', 'coconut'], ARRAY[]::TEXT[]),
('红咖喱', 'Red Curry', 'Kari Merah', '泰式红咖喱', 'lunch', 'thai', 'lunch', 20, 25, 4, 'medium', 450, ARRAY['spicy', 'coconut'], ARRAY[]::TEXT[]),
('泰式炒河粉', 'Pad Thai', 'Pad Thai', '泰式炒粿条', 'lunch', 'thai', 'lunch', 15, 15, 2, 'medium', 480, ARRAY['sweet-sour'], ARRAY['peanuts']),
('椰浆饭套餐', 'Nasi Lemak Set', 'Set Nasi Lemak', '椰浆饭配炸鸡、参巴鱿鱼', 'lunch', 'malay', 'lunch', 30, 40, 2, 'medium', 650, ARRAY['traditional', 'hearty'], ARRAY[]::TEXT[]),
('马来炒粿条', 'Char Kuey Teow Mamak', 'Char Kuey Teow Mamak', '印度风味炒粿条', 'lunch', 'indian', 'lunch', 15, 15, 2, 'medium', 520, ARRAY['spicy'], ARRAY[]::TEXT[]),
('椰浆鸡', 'Coconut Chicken', 'Ayam Masak Lemak', '椰浆炖鸡', 'lunch', 'malay', 'lunch', 20, 35, 4, 'easy', 480, ARRAY['coconut', 'mild'], ARRAY[]::TEXT[]),

-- 晚餐类 (Dinner) - 70道
('烤鸡', 'Roast Chicken', 'Ayam Panggang', '香料烤全鸡', 'dinner', 'malay', 'dinner', 30, 60, 4, 'medium', 520, ARRAY['grilled'], ARRAY[]::TEXT[]),
('烤鱼', 'Grilled Fish', 'Ikan Bakar', '香蕉叶包烤鱼', 'dinner', 'malay', 'dinner', 20, 25, 2, 'medium', 320, ARRAY['grilled', 'healthy'], ARRAY[]::TEXT[]),
('烤羊肉串', 'Lamb Skewers', 'Sate Kambing', '炭烤羊肉串', 'dinner', 'malay', 'dinner', 60, 15, 4, 'medium', 420, ARRAY['grilled'], ARRAY[]::TEXT[]),
('烤牛肉串', 'Beef Skewers', 'Sate Daging', '炭烤牛肉串', 'dinner', 'malay', 'dinner', 60, 15, 4, 'medium', 400, ARRAY['grilled'], ARRAY[]::TEXT[]),
('烤鸡翅', 'BBQ Chicken Wings', 'Sayap Ayam Bakar', '烧烤鸡翅', 'dinner', 'mixed', 'dinner', 60, 25, 4, 'easy', 380, ARRAY['grilled'], ARRAY[]::TEXT[]),
('火锅', 'Steamboat', 'Steamboat', '马来西亚火锅', 'dinner', 'chinese', 'dinner', 40, 60, 4, 'easy', 520, ARRAY['social', 'customizable'], ARRAY[]::TEXT[]),
('肉骨茶火锅', 'Bak Kut Teh Steamboat', 'Steamboat Bak Kut Teh', '药材火锅', 'dinner', 'chinese', 'dinner', 30, 90, 4, 'easy', 480, ARRAY['herbal'], ARRAY[]::TEXT[]),
('咖喱火锅', 'Curry Steamboat', 'Steamboat Kari', '咖喱汤火锅', 'dinner', 'indian', 'dinner', 30, 60, 4, 'easy', 550, ARRAY['spicy'], ARRAY[]::TEXT[]),
('粤式烧腊', 'Cantonese Roast', 'Siu Lap', '烧鸭叉烧', 'dinner', 'chinese', 'dinner', 120, 60, 4, 'hard', 580, ARRAY['traditional'], ARRAY[]::TEXT[]),
('烧鸭', 'Roast Duck', 'Itik Panggang', '脆皮烧鸭', 'dinner', 'chinese', 'dinner', 60, 90, 4, 'hard', 550, ARRAY['crispy'], ARRAY[]::TEXT[]),
('叉烧', 'Char Siu', 'Char Siew', '蜜汁叉烧', 'dinner', 'chinese', 'dinner', 240, 30, 4, 'medium', 480, ARRAY['sweet'], ARRAY[]::TEXT[]),
('烧肉', 'Roast Pork', 'Siew Yoke', '脆皮烧肉', 'dinner', 'chinese', 'dinner', 60, 60, 4, 'hard', 620, ARRAY['crispy'], ARRAY['halal']),
('北京烤鸭', 'Peking Duck', 'Bebek Peking', '北京烤鸭', 'dinner', 'chinese', 'dinner', 180, 60, 4, 'hard', 580, ARRAY['traditional'], ARRAY[]::TEXT[]),
('东坡肉', 'Braised Pork Belly', 'Babi Dongpo', '红烧五花肉', 'dinner', 'chinese', 'dinner', 30, 120, 4, 'medium', 680, ARRAY['rich'], ARRAY['halal']),
('红烧牛肉', 'Braised Beef', 'Daging Lembu Masak Merah', '红烧牛肉', 'dinner', 'chinese', 'dinner', 30, 90, 4, 'easy', 520, ARRAY['hearty'], ARRAY[]::TEXT[]),
('炖羊肉', 'Braised Lamb', 'Kambing Sup', '香料炖羊肉', 'dinner', 'chinese', 'dinner', 30, 90, 4, 'easy', 550, ARRAY['hearty'], ARRAY[]::TEXT[]),
('佛跳墙', 'Buddha Jumps Over Wall', 'Fo Tiao Qiang', '高汤炖海鲜', 'dinner', 'chinese', 'dinner', 60, 180, 6, 'hard', 420, ARRAY['luxury'], ARRAY[]::TEXT[]),
('盆菜', 'Poon Choi', 'Poon Choi', '九大簋盆菜', 'dinner', 'chinese', 'dinner', 90, 60, 8, 'hard', 680, ARRAY['festive', 'luxury'], ARRAY[]::TEXT[]),
('海鲜煲', 'Seafood Hotpot', 'Periuk Seafood', '海鲜砂锅', 'dinner', 'chinese', 'dinner', 30, 30, 4, 'medium', 480, ARRAY['seafood'], ARRAY[]::TEXT[]),
('鱼头米粉', 'Fish Head Noodle', 'Meehoon Sup Ikan', '鱼头米粉汤', 'dinner', 'chinese', 'dinner', 30, 45, 4, 'medium', 420, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('鱼片米粉', 'Fish Slice Noodle', 'Meehoon Sup Ikan Hiris', '鱼片米粉汤', 'dinner', 'chinese', 'dinner', 20, 20, 2, 'easy', 380, ARRAY['light'], ARRAY[]::TEXT[]),
('鸡丝河粉', 'Chicken Noodle Soup', 'Sup Kuey Teow Ayam', '鸡丝河粉汤', 'dinner', 'chinese', 'dinner', 30, 30, 2, 'easy', 420, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('云吞汤', 'Wonton Soup', 'Sup Wantan', '清汤云吞', 'dinner', 'chinese', 'dinner', 30, 15, 2, 'medium', 280, ARRAY['light'], ARRAY[]::TEXT[]),
('干捞云吞面', 'Dry Wonton Noodles', 'Mee Wantan Kering', '干捞云吞面', 'dinner', 'chinese', 'dinner', 30, 15, 2, 'medium', 450, ARRAY['savory'], ARRAY[]::TEXT[]),
('煲仔饭', 'Claypot Rice', 'Nasi Periuk Tanah', '砂锅饭', 'dinner', 'chinese', 'dinner', 20, 40, 2, 'medium', 520, ARRAY['traditional'], ARRAY[]::TEXT[]),
('腊味煲仔饭', 'Lap Mei Claypot', 'Nasi Periuk Lap Mei', '腊肠腊肉饭', 'dinner', 'chinese', 'dinner', 20, 40, 2, 'medium', 580, ARRAY['traditional'], ARRAY[]::TEXT[]),
('田鸡粥', 'Frog Porridge', 'Bubur Katak', '田鸡粥', 'dinner', 'chinese', 'dinner', 30, 45, 4, 'medium', 320, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('皮蛋瘦肉粥', 'Century Egg Porridge', 'Bubur Telur Pitan', '皮蛋瘦肉粥', 'dinner', 'chinese', 'dinner', 20, 60, 4, 'easy', 280, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('鱼片粥', 'Fish Porridge', 'Bubur Ikan', '鱼片粥', 'dinner', 'chinese', 'dinner', 20, 40, 4, 'easy', 260, ARRAY['light'], ARRAY[]::TEXT[]),
('海鲜粥', 'Seafood Porridge', 'Bubur Seafood', '海鲜粥', 'dinner', 'chinese', 'dinner', 30, 40, 4, 'medium', 320, ARRAY['seafood'], ARRAY[]::TEXT[]),
('潮州粥', 'Teochew Porridge', 'Bubur Teochew', '潮州配菜粥', 'dinner', 'chinese', 'dinner', 30, 30, 4, 'easy', 380, ARRAY['traditional'], ARRAY[]::TEXT[]),
('砂锅鱼头', 'Claypot Fish Head', 'Kepala Ikan Periuk Tanah', '砂锅鱼头煲', 'dinner', 'chinese', 'dinner', 30, 30, 4, 'medium', 420, ARRAY['comfort-food'], ARRAY[]::TEXT[]),
('砂锅豆腐', 'Claypot Tofu', 'Tauhu Periuk Tanah', '砂锅豆腐煲', 'dinner', 'chinese', 'dinner', 20, 25, 4, 'easy', 320, ARRAY['vegetarian'], ARRAY[]::TEXT[]),
('香锅鸡', 'Fragrant Pot Chicken', 'Ayam Periuk Wangi', '干锅鸡', 'dinner', 'chinese', 'dinner', 25, 30, 4, 'medium', 480, ARRAY['spicy'], ARRAY[]::TEXT[]),
('水煮鱼', 'Boiled Fish in Chili', 'Ikan Rebus Cili', '水煮鱼', 'dinner', 'chinese', 'dinner', 25, 20, 4, 'medium', 380, ARRAY['spicy'], ARRAY[]::TEXT[]),
('水煮牛', 'Boiled Beef in Chili', 'Daging Rebus Cili', '水煮牛肉', 'dinner', 'chinese', 'dinner', 25, 20, 4, 'medium', 450, ARRAY['spicy'], ARRAY[]::TEXT[]),
('酸菜鱼', 'Sour Cabbage Fish', 'Ikan Kobis Asam', '酸菜鱼', 'dinner', 'chinese', 'dinner', 25, 25, 4, 'medium', 380, ARRAY['sour'], ARRAY[]::TEXT[]),
('剁椒鱼头', 'Chopped Chili Fish Head', 'Kepala Ikan Cili', '剁椒鱼头', 'dinner', 'chinese', 'dinner', 30, 25, 4, 'medium', 350, ARRAY['spicy'], ARRAY[]::TEXT[]),
('椒盐排骨', 'Salt Pepper Ribs', 'Tulang Lada Garam', '椒盐排骨', 'dinner', 'chinese', 'dinner', 30, 25, 4, 'medium', 520, ARRAY['crispy'], ARRAY[]::TEXT[]),
('糖醋排骨', 'Sweet Sour Ribs', 'Tulang Masam Manis', '糖醋排骨', 'dinner', 'chinese', 'dinner', 30, 25, 4, 'medium', 550, ARRAY['sweet-sour'], ARRAY[]::TEXT[]),
('红烧排骨', 'Braised Ribs', 'Tulang Masak Merah', '红烧排骨', 'dinner', 'chinese', 'dinner', 20, 45, 4, 'easy', 520, ARRAY['savory'], ARRAY[]::TEXT[]),
('盐焗鸡', 'Salt Baked Chicken', 'Ayam Garam Bakar', '盐焗鸡', 'dinner', 'chinese', 'dinner', 30, 60, 4, 'medium', 480, ARRAY['traditional'], ARRAY[]::TEXT[]),
('白切鸡', 'Poached Chicken', 'Ayam Putih', '白切鸡', 'dinner', 'chinese', 'dinner', 15, 40, 4, 'easy', 420, ARRAY['light'], ARRAY[]::TEXT[]),
('醉鸡', 'Drunken Chicken', 'Ayam Mabuk', '酒香鸡', 'dinner', 'chinese', 'dinner', 120, 30, 4, 'medium', 460, ARRAY['aromatic'], ARRAY[]::TEXT[]),
('贵妃鸡', 'Imperial Chicken', 'Ayam Permaisuri', '贵妃鸡', 'dinner', 'chinese', 'dinner', 30, 40, 4, 'medium', 480, ARRAY['luxury'], ARRAY[]::TEXT[]),
('左宗鸡', 'General Tso Chicken', 'Ayam Jeneral', '左宗棠鸡', 'dinner', 'chinese', 'dinner', 25, 20, 4, 'medium', 520, ARRAY['spicy'], ARRAY[]::TEXT[]),
('柠檬鸡', 'Lemon Chicken', 'Ayam Lemon', '柠檬鸡', 'dinner', 'chinese', 'dinner', 20, 20, 4, 'easy', 450, ARRAY['tangy'], ARRAY[]::TEXT[]),
('橙汁鸡', 'Orange Chicken', 'Ayam Oren', '橙汁鸡', 'dinner', 'chinese', 'dinner', 20, 20, 4, 'easy', 480, ARRAY['sweet'], ARRAY[]::TEXT[]),
('蜜汁鸡翅', 'Honey Chicken Wings', 'Sayap Ayam Madu', '蜜汁鸡翅', 'dinner', 'chinese', 'dinner', 60, 30, 4, 'easy', 450, ARRAY['sweet'], ARRAY[]::TEXT[]),
('可乐鸡翅', 'Cola Chicken Wings', 'Sayap Ayam Cola', '可乐鸡翅', 'dinner', 'chinese', 'dinner', 15, 30, 4, 'easy', 420, ARRAY['sweet'], ARRAY[]::TEXT[]);

-- 菜品与食材关联数据将在下一个文件中

